name: 'Setup R environment'
description: 'Setup a R environment and add it to the PATH'
author: 'Jim Hester'
inputs:
  r-version:
    description: 'Version range or exact version of an R version to use.'
    default: 'release'
  rtools-version:
    description: 'Exact version of Rtools to use. Default uses latest suitable
    rtools for the given version of R.'
  Ncpus:
    description: 'Value to set the R option `Ncpus` to.'
    default: '1'
  crayon.enabled:
    description: 'Value to set the R option `crayon.enabled` to.'
    default: 'TRUE'
  remove-openmp-macos:
    description: 'If true, remove `-fopenmp` from the default compilation
    flags, e.g. `SHLIB_OPENMP_CFLAGS`, as the macOS Command Line Tools do not
    support OpenMP'
    default: true
  http-user-agent:
    descripton: 'If "default", sets the HTTPUserAgent option to e.g. for R
    3.6.3 running on macOS Catalina, "R/3.6.3 R (3.6.3 x86_64-apple-darwin17.0
    x86_64 darwin17.0) on GitHub Actions". Otherwise uses whatever value is
    set.'
    default: 'default'
runs:
  using: 'node12'
  main: 'lib/setup-r.js'
