name: 'goodpractice'
description: 'Runs the goodpractice package on a repository and puts the results in an annotation'
author: 'Jim Hester'
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
runs:
  using: 'node12'
  main: 'lib/main.js'
