name: 'pr-fetch'
description: 'Fetch changes from a Pull Request branch'
author: 'Jim Hester'
inputs:
  repo-token:
    description: 'Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
runs:
  using: 'node16'
  main: 'lib/main.js'
