name: Setup and run rchk test
description: Setup and run rchk test
inputs:
  setup-only:
    description: Setup rchk only and skip running the test.
    required: false
    default: false
  run-only:
    description: Skip the setup step and run the test directly assuming that setup was run.
    required: false
    default: false
  cache-version:
    description: The version of the cache, change this from the default (rchk-1) to start over with a fresh cache
    required: false
    default: rchk-1
runs:
  using: 'composite'
  steps:
    - if: inputs.run-only != 'true'
      name: Setup rchk
      run: bash $GITHUB_ACTION_PATH/setup.sh
      shell: bash
    - if: inputs.setup-only != 'true' && inputs.run-only != 'true'
      uses: r-lib/actions/setup-r-dependencies@v1
      with:
        cache-version: ${{ inputs.cache-version }}
    - if: inputs.setup-only != 'true'
      name: Run rchk
      run: |
        bash $GITHUB_ACTION_PATH/run.sh
      shell: bash
