on:
  workflow_dispatch:

name: Rtools test

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: windows-latest

    name: Windows, R ${{ matrix.config.r }}, Rtools ${{ matrix.config.rtools-version }}

    strategy:
      fail-fast: false
      matrix:
        config:
          # the default is rtools40 here
          - { r: 'release'                       }
          # manually select rtools42
          - { r: 'release', rtools-version: '42' }
          # defaults to rtools43
          - { r: 'devel'                         }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - uses: ./setup-pandoc

      - uses: ./setup-r
        with:
          r-version: ${{ matrix.config.r }}
          rtools-version: ${{ matrix.config.rtools-version }}
          use-public-rspm: true

      - name: "Check what version of rtools is installed"
        run: |
          ls c:/

      - name: "Install package from source"
        run: |
          install.packages("filelock", type = "source")
        shell: Rscript {0}
